DROP TABLE studierende_veranstaltung_gruppe;
-- DROP TABLE studierende_veranstaltung_gruppe_pref;
DROP TABLE studierende;
DROP TABLE veranstaltung_gruppe;
DROP TABLE veranstaltung;
DROP TABLE veranstaltungstyp;
DROP TABLE liste;
DROP TABLE modul_studiengang;
DROP TABLE modul;
DROP TABLE studiengang;
DROP TABLE orte;
